name: CI/CD Pipeline for UserManagementBackend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          EC2_USER: ${{ secrets.EC2_USER }}  
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          # Setup SSH
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          
          # Deploy
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP '
            cd ~/UserManagementBackend
            git pull origin main
            go mod tidy
            go build -o main ./cmd/main.go
            sudo systemctl restart usermanagement.service
          '
          
          # Cleanup
<<<<<<< HEAD
          rm -f key.pem
=======
          rm -f key.pem
>>>>>>> 59f8c75 (added health route)
